Repository deshima-dev/demerge, pull requests merged in 2023-11, with the labels that each got.

#72 DESHIMA2.0の実データの読み込みとfshiftのDEMSへの出力を可能にする
  .devcontainer/devcontainer.json
  .gitignore
  demerge/calc_resonance_params.py
  demerge/demerge.py
  demerge/make_reduced_fits.py
  demerge/merge_function.py
  demerge/merge_to_dems.py
  demerge/run.sh
  poetry.lock
  pyproject.toml
  tests/mktd.sh
  tests/tdmaker.py
  tests/test_merge_function.py
  tests/test_merge_to_dems.py
Labels: feature

#75 Assign long_name and units to DEMS based on loadtype
  .devcontainer/devcontainer.json
  demerge/merge_to_dems.py
  poetry.lock
  tests/test_merge_to_dems.py
Labels: feature

#77 Add exception handling when MKID fit errors are missing
  .github/workflows/tests.yaml
  demerge/calc_resonance_params.py
Labels: bug

#79 Add option for no plotting by default
  demerge/run.sh
Labels: feature

#82 Release v2.8.0
  .gitmodules
  CITATION.cff
  README.md
  demerge/__init__.py
  demerge/calc_resonance_params.py
  demerge/demerge.py
  demerge/merge_function.py
  demerge/plot.py
  pyproject.toml
Labels: refactoring, release

#84 Fix IndexError raised in df/f-to-Tsky conversion
  .devcontainer/devcontainer.json
  .github/workflows/pypi.yaml
  .github/workflows/tests.yaml
  CITATION.cff
  README.md
  demerge/__init__.py
  demerge/merge_function.py
  demerge/merge_to_dems.py
  pyproject.toml
  tests/test_merge_function.py
Labels: bug, release

#86 Release v2.8.1
  CITATION.cff
Labels: release

#88 Release v2.8.1
  CITATION.cff
Labels: release

#91 Add default cabin temperature
  CITATION.cff
  README.md
  demerge/__init__.py
  demerge/merge_function.py
  pyproject.toml
  tests/test_merge_to_dems.py
Labels: bug, release
